### PR TITLE
Update the 2D 

### PR DESCRIPTION
**Pull request by Murii**
New : - scale function
          - flip function 
          -camera works with 2d objects!

### CODE REVIEW

**Comment by Sponk** [comment]
Could you please correct your code so I can finally merge it?

**Comment by Murii** [comment]
I have no idea what's wrong. For me it's working just fine.

**Comment by Sponk** [comment]
Just do what I commented on your code. The compiler we use for compilation is older than the one you use and does not support Java like initialization in classes.

**Comment by Sponk** [comment]
Can you please fix your code? I don't want to reject this code again.

**Comment by Sponk** [comment]
I tested your changes and read some of your code. 
First: I like the way the collision systems works. It is clean and simple.

And I saw that you documented some more code, that's good :)

But there still are some complaints to make. One of which is code formatting. Please configure your editor to place "{" and "}" the right way while having a consistent use of tabs instead of spaces.

Another problem I have with the code is the camera offset code. Every canvas should have its own camera so you can move them independently. Currently only one camera is possible. It would not be a big change, just move the offset code to the Canvas class and apply the offset there when rendering.

Then I can hopefully agree completely with your code and merge it :)

**Comment by Sponk** [comment]
I'll simple take your PR apart and push it one change at a time while cleaning up the formatting.
Please make sure that this does not happen again in future!

**Comment by Sponk** [comment]
https://github.com/Sponk/NeoEditor/commit/fa319113977f14088e6ee7d1760fccbc5094d555

Thanks for your contribution!

**Pull request closed without merging**
