### PR TITLE
Update Widget.lua

### PR DESCRIPTION
**Pull request by Murii**

### CODE REVIEW

**Comment by Sponk** [comment]
Thank you for your contribution!

**Comment by Murii** [comment]
I have something pretty big prepared but I dont know how to use the classes.Maybe I could send you the class and make the changes so that it`ll work as a class?

**Comment by Sponk** [comment]
Yeah, sure

**Comment by Sponk** [comment]
Btw: I'm using the following script to create classes

http://lua-users.org/wiki/SimpleLuaClasses

**Pull request merged**
