### PR TITLE
Create Utils.lua

### PR DESCRIPTION
**Pull request by Murii**
Usage : 

	local a = Utils.create()
	print(a:random(30,130))

### CODE REVIEW

**Comment by Murii** [comment]
Also I could add game states + entities sistem + collision detection(no box2d).Interested?And latter on Tilemaps

**Comment by Sponk** [comment]
Thank you, those are a nice addition to the library.
One thing though: How about making those methods static so you can access them without instantiating Utils since these methods do not depend on any object or state.
You could then simply do "Utils.random(30,130)" without creating a new object beforehand.

About the C++ side: I will write a small guide on how to extend the API in a cross-platform way. This should help you to do the changes you need.

Btw: The Lua API is distributed under the terms and conditions of the Zlib license like the core engine. I still need to copy a license header into there.

**Comment by Murii** [comment]
I thought the same regarding the Utils it should be global.I`ll look into it today! Also a C++ doc is welcomed!

**Comment by Akira1San** [comment]
hi Murii
Whats this "game states + entities system"?

**Comment by Murii** [comment]
@Akira1San Just some basic features that every engine should have.The entities system is aleardy done.Game states are on TODO list

**Comment by Akira1San** [comment]
Ok, i see.

**Pull request merged**
