### PR TITLE
Set the position of your Entity!

### PR DESCRIPTION
**Pull request by Murii**

### CODE REVIEW

**Comment by Sponk** [comment]
Thank you, this method actually is already implemented in Object3d.lua:
https://github.com/Sponk/NeoEditor/blob/development/SDK/LuaApi/Object3d.lua

OEntity inherits it and you can simply use it.

**Comment by BitPuffin** [comment]
So this is a documentation issue then? Does the lua docs show inherited "methods"?

**Comment by Sponk** [comment]
Well, this API will be removed anyway since the full C++ API is now available in Lua through an auto generated wrapper.

**Comment by BitPuffin** [comment]
I know. But since you "own" the documentation tool, you can manually add support for your class library thingy and check inherited members

**Comment by Sponk** [comment]
Won't merge this  PR because the functionality already exists.
Thank you anyway!

**Pull request closed without merging**
